version: "3.9"
services:
  sut:
    build:
      context: .
      args:
        OPENMLDB_VERSION: 0.3.0
    command: >
      bash -c "
      ./init.sh && python3 import.py &&
      python3 train.py ./fe.sql /tmp/model.txt &&
      ./start_predict_server.sh ./fe.sql /tmp/model.txt &&
      python3 predict.py"
