name: Docker

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
    paths:
      - demo/predict-taxi-trip-duration-nb/**/*

env:
  IMAGE_NAME: openmldb

jobs:
  build-and-publish:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker Compose Test
        working-directory: demo/predict-taxi-trip-duration-nb
        run: |
          docker-compose -f docker-compose.test.yml -- up

      - name: Decide the Tag
        if: ${{ github.event_name == 'push' }}
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Strip "docker" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

          # Use Docker `latest` tag convention
          [ "$VERSION" == "main" ] && VERSION=latest

          echo VERSION=$VERSION

          GHCR_TAG=$IMAGE_ID:$VERSION
          DOCKERHUB_TAG=${{ secrets.DOCKERHUB_REPO }}/$IMAGE_NAME:$VERSION
          echo "GitHub Docker Registry Tag: $GHCR_TAG"
          echo "DockerHub Tag: "
          echo "COMMIT=${{ github.sha }}"

          echo "GHCR_TAG=$GHCR_TAG" >> $GITHUB_ENV
          echo "DOCKERHUB_TAG=$DOCKERHUB_TAG" >> $GITHUB_ENV

      - name: Decide Push
        run: |
          if [[ ${{ github.event_name }} = 'push' ]]; then
            echo "PUSH=true" >> $GITHUB_ENV
          else
            echo "PUSH=false" >> $GITHUB_ENV
          fi

      - name: Login to Docker Hub
        if: ${{ github.event_name == 'push' }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        if: ${{ github.event_name == 'push' }}
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Build And Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: demo/predict-taxi-trip-duration-nb
          push: ${{ env.PUSH }}
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.GHCR_TAG }}
            ${{ env.DOCKERHUB_TAG }}
