name: monitoring integration test

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/monitoring.yml'
      - 'monitoring/**'
  pull_request:
    paths:
      - '.github/workflows/monitoring.yml'
      - 'monitoring/**'
  workflow_dispatch:

permissions:
  checks: write
  pull-requests: write

jobs:
  src-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: service up
        working-directory: monitoring
        run: |
          docker compose --file docker-compose.yml up -d grafana

      - name: verbose services
        working-directory: monitoring
        # ensure all services is up
        run: |
          sleep 60
          docker compose --file docker-compose.yml ps -a

      - name: verbose exporter log
        working-directory: monitoring
        run: |
          docker compose --file docker-compose.yml logs openmldb-exporter

      - name: run tests
        working-directory: monitoring
        run: |
          docker compose --file docker-compose.yml up --no-recreate --exit-code-from testing testing

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          check_name: Monitoring integration test
          comment_title: Monitoring integration test
          files: |
            ./monitoring/pytest.xml

  prod-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: service up
        working-directory: monitoring
        run: |
          docker compose --file docker-compose.yml --build-arg ENV_TYPE=prod up -d grafana

      - name: run tests
        working-directory: monitoring
        run: |
          docker compose --file docker-compose.yml --build-arg ENV_TYPE=prod  up --no-recreate --exit-code-from testing testing
