name: publish-test-result-from-fork

on:
  # the action will only run on dependabot/fork pull request
  workflow_run:
    workflows: ["cicd"]
    types:
      - completed

jobs:
  test-results:
    if: >
      github.event.workflow_run.conclusion != 'skipped' && (
         github.event.sender.login == 'dependabot[bot]' ||
         github.event.workflow_run.head_repository.full_name != github.repository
      )
    name: linux test report
    uses: team-317/OpenMLDB/.github/workflows/publish-test-result-from-fork-action.yml@reuse_workflow
    with:
      commit: ${{ github.event.workflow_run.head_sha }}
      files: artifacts/linux-ut-result-*/**/*.xml
      check_name: Linux Test Report
      comment_title: Linux Test Report